import sys.io.File;
import sys.FileSystem;

/**
 * Reads the conformance columns and says what disagrees with what.
 *
 * Kept apart from the runner deliberately. A runner that decided what counted as agreement would
 * have to be built into every column, and then two columns could disagree about the definition
 * rather than about the answer. `ConformanceProbe` reports what happened; everything that is a
 * judgement is here, once.
 *
 * **A compiled column is compared against its own target's interpreter, not against eval.** The two
 * questions look alike and are not the same one. Whether cppia agrees with the interpreter is about
 * this library. Whether the interpreter on one target agrees with the interpreter on another is
 * about what survived dead code elimination in two different builds, which is a property of those
 * builds.
 * Mixing them produces rows that read as compiler faults and are not, which is what the old table
 * marked with a star and left to the reader.
 */
class Table {
	/** Where the columns are, and where the generated page goes. */
	static var dir:String = 'bin_test/conformance';

	static var page:String = 'docs/support-table.md';

	/** Every case, in the order the runner offered them. */
	static var cases:Array<Entry> = [];

	/** What each mode answered, by case index. */
	static var columns:Map<String, Map<Int, Cell>> = [];

	/** Which interpreted column each compiled one is judged against. */
	static var reference:Map<String, String> = [
		'hxcpp-cppia' => 'hxcpp-interp',
		'hxcpp-cppia-jit' => 'hxcpp-interp',
		'hl-bytecode' => 'hl-interp'
	];

	/** The interpreted columns, compared to each other rather than to anything. */
	static var interpreted:Array<String> = ['eval-interp', 'hxcpp-interp', 'hl-interp'];

	public static function main():Void {
		var section:String = 'basics';

		Conformance.run(function(label:String, body:String, want:Null<String>, ?extra:String, ?before:String):Void {
			cases.push({label: label, want: want, section: section});
		}, function(name:String):Void {
			section = name;
		});

		for (mode in interpreted)
			read(mode);

		for (mode in reference.keys())
			read(mode);

		var out:StringBuf = new StringBuf();
		var failures:Int = 0;

		out.add('# Support table\n\n');
		out.add('Generated by `sh test/lib/conformance.sh` and `haxe test/lib/table.hxml`. Do not edit.\n\n');
		out.add('' + cases.length + ' cases, ' + present().length + ' of 6 columns collected.\n\n');

		failures += assertions(out);
		failures += parity(out);
		categories(out);
		reach(out);
		full(out);

		if (!FileSystem.exists('docs'))
			FileSystem.createDirectory('docs');

		File.saveContent(page, out.toString());
		Sys.println('wrote ' + page);
		Sys.exit(failures == 0 ? 0 : 1);
	}

	/**
	 * Every category against every mode, which is the view that says what works rather than what broke.
	 *
	 * The rest of this page lists problems, so a clean run says almost nothing and a reader cannot
	 * tell a suite that passed from one that never ran. This is the other direction: one row per part
	 * of the library, one column per mode, and a cell saying how much of that part that mode got
	 * right.
	 *
	 * A cell counts a case as good on its own terms. An asserted case is good when it produced the
	 * answer written down for it; a case with no expected answer is good when it agrees with the
	 * interpreter of its own target, because that is the only claim anybody made about it. Refusals
	 * are counted apart and are not failures: the module was interpreted instead, which is slower and
	 * not wrong.
	 *
	 * @param out The page being built.
	 */
	static function categories(out:StringBuf):Void {
		out.add('## What works, by part and by mode\n\n');

		var modes:Array<String> = present();

		if (modes.length == 0) {
			out.add('No columns were collected.\n\n');
			return;
		}

		var order:Array<String> = [];
		var total:Map<String, Int> = [];

		for (entry in cases) {
			if (!total.exists(entry.section)) {
				order.push(entry.section);
				total.set(entry.section, 0);
			}

			total.set(entry.section, total.get(entry.section) + 1);
		}

		/**
		 * Named `<target>-<how a script runs>`, because those are two independent axes and a name that
		 * blurred them was read wrong: `cpp-interp` looks like a C++ interpreter and is the library's
		 * own tree-walking interpreter, compiled into an hxcpp binary.
		 */
		out.add('Each column is one target running a script one way:\n\n');
		out.add('| column | target | how the script runs |\n| --- | --- | --- |\n');
		out.add('| `eval-interp` | Haxe eval | tree-walking interpreter |\n');
		out.add('| `hxcpp-interp` | hxcpp | tree-walking interpreter |\n');
		out.add('| `hxcpp-cppia` | hxcpp | cppia bytecode, JIT off |\n');
		out.add('| `hxcpp-cppia-jit` | hxcpp | cppia bytecode, JIT on |\n');
		out.add('| `hl-interp` | HashLink (HL/C binary) | tree-walking interpreter |\n');
		out.add('| `hl-bytecode` | HashLink (HL/C binary) | HashLink bytecode, jitted |\n\n');

		out.add('`n/m` is how many of that part\'s cases the mode got right, and `+3r` beside it means three\n');
		out.add('of them were refused: the module was declined and interpreted instead, which costs speed\n');
		out.add('rather than correctness. **Bold** marks a part where something is actually wrong.\n\n');

		out.add('| part | cases | ' + modes.join(' | ') + ' |\n');
		out.add('| --- | --- | ' + [for (m in modes) '---'].join(' | ') + ' |\n');

		/** The same grid without the markup, so a runner can show it without opening the page. */
		var console:Array<String> = [pad('part', 14) + pad('cases', 7) + [for (m in modes) pad(m, 17)].join('')];

		for (name in order) {
			var row:Array<String> = ['| ' + name, '' + total.get(name)];
			var plain:String = pad(name, 14) + pad('' + total.get(name), 7);

			for (mode in modes) {
				var good:Int = 0;
				var seen:Int = 0;
				var refused:Int = 0;

				for (i in 0...cases.length) {
					if (cases[i].section != name)
						continue;

					var cell:Null<Cell> = columns.get(mode).get(i);
					if (cell == null)
						continue;

					seen++;

					if (cell.status == 'refused') {
						refused++;
						good++;
						continue;
					}

					if (settled(mode, i, cell))
						good++;
				}

				var text:String = seen == 0 ? '-' : good + '/' + seen + (refused > 0 ? ' +' + refused + 'r' : '');
				row.push(good < seen ? '**' + text + '**' : text);
				plain += pad(text + (good < seen ? ' !' : ''), 17);
			}

			out.add(row.join(' | ') + ' |\n');
			console.push(plain);
		}

		out.add('\n');

		Sys.println('');
		Sys.println('-- what works, by part and by mode --');
		for (line in console)
			Sys.println(line);
		Sys.println('');
		Sys.println('n/m right, +Nr refused and interpreted instead, ! something wrong');
	}

	/** @param s The text. @param width How wide. @return It, padded to that width. */
	static function pad(s:String, width:Int):String {
		var out:String = s;
		while (out.length < width)
			out += ' ';
		return out;
	}

	/**
	 * @param mode The column.
	 * @param i The case index.
	 * @param cell What that column answered.
	 * @return Whether the case came out right, on whichever terms apply to it.
	 */
	static function settled(mode:String, i:Int, cell:Cell):Bool {
		var want:Null<String> = cases[i].want;

		if (want != null)
			return cell.status == 'ok' && cell.value == want;

		/** No answer was written down, so the interpreter of this mode's own target is the claim. */
		var against:Null<String> = reference.get(mode);

		/**
		 * An interpreted column is that claim rather than being judged against it, so a case with no
		 * expected answer cannot be wrong here: throwing is what half the frontier cases are for, and
		 * counting that as a miss marked the whole `refusals` part red for working exactly as written.
		 * Ending the process is the one outcome still worth reporting, because nothing about a case
		 * says the runtime may not survive it.
		 */
		if (against == null || !columns.exists(against))
			return cell.status != 'killed';

		var ref:Null<Cell> = columns.get(against).get(i);

		if (ref == null)
			return cell.status != 'killed';

		return cell.status == ref.status && cell.value == ref.value;
	}

	/**
	 * Cases the corpus asserts an answer for, where a column gave a different one.
	 *
	 * These are the strong claims: somebody wrote down what the answer is, so a column that misses
	 * one has a bug rather than a reading.
	 *
	 * @param out The page being built.
	 * @return How many failed.
	 */
	static function assertions(out:StringBuf):Int {
		var rows:Array<String> = [];

		for (i in 0...cases.length) {
			var want:Null<String> = cases[i].want;
			if (want == null)
				continue;

			for (mode in present()) {
				var cell:Null<Cell> = columns.get(mode).get(i);
				if (cell == null || cell.status == 'refused')
					continue;

				if (cell.status == 'ok' && cell.value == want)
					continue;

				rows.push('| ' + cases[i].label + ' | ' + mode + ' | ' + want + ' | ' + render(cell) + ' |');
			}
		}

		out.add('## Asserted cases that missed\n\n');

		if (rows.length == 0) {
			out.add('None. Every case with a written answer produced it in every column that ran it.\n\n');
			return 0;
		}

		out.add('| case | mode | wanted | got |\n| --- | --- | --- | --- |\n');
		out.add(rows.join('\n'));
		out.add('\n\n');
		return rows.length;
	}

	/**
	 * Compiled columns against their own target's interpreter.
	 *
	 * A cell whose `via` is `interp` in a compiled column is called out on its own, because it is the
	 * one outcome that looks like success and is not: the module was refused or the entry was never
	 * replaced, the interpreter ran instead, and the column is quietly comparing the interpreter with
	 * itself.
	 *
	 * @param out The page being built.
	 * @return How many disagreed.
	 */
	static function parity(out:StringBuf):Int {
		out.add('## Compiled against interpreted, per target\n\n');

		var wrong:Int = 0;
		var rows:Array<String> = [];
		var modes:Array<String> = [for (m in reference.keys()) if (columns.exists(m)) m];
		modes.sort(Reflect.compare);

		for (mode in modes) {
			var against:String = reference.get(mode);

			if (!columns.exists(against)) {
				out.add('`' + mode + '` was collected but `' + against + '` was not, so it cannot be judged.\n\n');
				continue;
			}

			var agree:Int = 0;
			var differs:Int = 0;
			var refused:Int = 0;
			var fellBack:Int = 0;
			var killed:Int = 0;

			for (i in 0...cases.length) {
				switch (verdict(mode, against, i)) {
					case 'agrees': agree++;
					case 'refused': refused++;
					case 'fell back': fellBack++;
					case 'killed': killed++;
					case 'absent':
					case other:
						differs++;
						rows.push('| ' + cases[i].label + ' | ' + mode + ' | ' + render(columns.get(against).get(i)) + ' | '
							+ render(columns.get(mode).get(i)) + ' |');
				}
			}

			wrong += differs;
			out.add('**' + mode + '** against `' + against + '`: ' + agree + ' agree, **' + differs + ' differ**, '
				+ refused + ' refused, ' + fellBack + ' fell back to the interpreter, ' + killed + ' killed the process.\n\n');
		}

		if (rows.length > 0) {
			out.add('| case | mode | interpreted | compiled |\n| --- | --- | --- | --- |\n');
			out.add(rows.join('\n'));
			out.add('\n\n');
		}

		return wrong;
	}

	/**
	 * Where two interpreted columns disagree, which is about the builds rather than the library.
	 *
	 * Reported and not counted. What a script can reach is decided by what survived dead code
	 * elimination in that host, so `haxe.Json` answering on one target and not another is a fact
	 * about those two binaries.
	 *
	 * @param out The page being built.
	 */
	static function reach(out:StringBuf):Void {
		var have:Array<String> = [for (m in interpreted) if (columns.exists(m)) m];

		out.add('## Where the interpreter itself reads differently per target\n\n');

		if (have.length < 2) {
			out.add('Fewer than two interpreted columns were collected.\n\n');
			return;
		}

		var rows:Array<String> = [];

		for (i in 0...cases.length) {
			var first:String = render(columns.get(have[0]).get(i));
			var same:Bool = true;

			for (mode in have)
				if (render(columns.get(mode).get(i)) != first)
					same = false;

			if (same)
				continue;

			rows.push('| ' + cases[i].label + ' | ' + [for (mode in have) render(columns.get(mode).get(i))].join(' | ') + ' |');
		}

		if (rows.length == 0) {
			out.add('Nowhere. Every interpreted column read the same.\n\n');
			return;
		}

		out.add('' + rows.length + ' of ' + cases.length + ' cases. This is reachability, not semantics.\n\n');
		out.add('| case | ' + have.join(' | ') + ' |\n| --- | ' + [for (m in have) '---'].join(' | ') + ' |\n');
		out.add(rows.join('\n'));
		out.add('\n\n');
	}

	/**
	 * Every case in every column, for looking one up.
	 *
	 * @param out The page being built.
	 */
	static function full(out:StringBuf):Void {
		var have:Array<String> = present();

		out.add('<details>\n<summary>Every case, every column</summary>\n\n');
		out.add('| # | case | ' + have.join(' | ') + ' |\n| --- | --- | ' + [for (m in have) '---'].join(' | ') + ' |\n');

		for (i in 0...cases.length)
			out.add('| ' + i + ' | ' + cases[i].label + ' | ' + [for (mode in have) render(columns.get(mode).get(i))].join(' | ') + ' |\n');

		out.add('\n</details>\n');
	}

	/**
	 * How one compiled column did on one case.
	 *
	 * @param mode The compiled column.
	 * @param against The interpreted column to judge it by.
	 * @param i The case.
	 * @return One of `agrees`, `differs`, `refused`, `fell back`, `killed`, `absent`.
	 */
	static function verdict(mode:String, against:String, i:Int):String {
		var cell:Null<Cell> = columns.get(mode).get(i);
		var ref:Null<Cell> = columns.get(against).get(i);

		if (cell == null || ref == null)
			return 'absent';

		if (cell.status == 'killed')
			return 'killed';

		if (cell.status == 'refused')
			return 'refused';

		/**
		 * The one outcome that looks like a pass and is not. A refused module falls back to the
		 * interpreter, so this row would agree with the interpreted column by construction, and
		 * counting it as agreement is how a compiled column reports itself entirely green while
		 * compiling nothing.
		 */
		if (cell.via == 'interp')
			return 'fell back';

		return render(cell) == render(ref) ? 'agrees' : 'differs';
	}

	/** @return A cell as one readable string. */
	static function render(cell:Null<Cell>):String {
		if (cell == null)
			return '-';

		return switch (cell.status) {
			case 'ok': cell.value;
			case 'threw': 'threw ' + cell.value;
			case 'refused': 'refused: ' + cell.value;
			case 'killed': '**killed**';
			case other: other + ' ' + cell.value;
		}
	}

	/** @return The columns that were collected, in a fixed order. */
	static function present():Array<String> {
		return [for (m in ['eval-interp', 'hxcpp-interp', 'hxcpp-cppia', 'hxcpp-cppia-jit', 'hl-interp', 'hl-bytecode']) if (columns.exists(m)) m];
	}

	/**
	 * Reads one column, when it is there.
	 *
	 * @param mode The mode's name, which is also its file's.
	 */
	static function read(mode:String):Void {
		var path:String = dir + '/' + mode + '.tsv';

		if (!FileSystem.exists(path))
			return;

		var found:Map<Int, Cell> = [];

		for (line in File.getContent(path).split('\n')) {
			var parts:Array<String> = StringTools.trim(line).split('\t');
			if (parts.length < 5)
				continue;

			var index:Null<Int> = Std.parseInt(parts[0]);
			if (index == null)
				continue;

			found.set(index, {status: parts[2], via: parts[3], value: parts[4]});
		}

		columns.set(mode, found);
	}
}

/** One case, as the list declares it. */
typedef Entry = {
	var label:String;
	var want:Null<String>;

	/** Which part of the library the case is about, for the per-category report. */
	var section:String;
}

/** What one mode answered for one case. */
typedef Cell = {
	var status:String;
	var via:String;
	var value:String;
}
