/**
 * Writes the benchmark corpus out as ordinary Haxe, for the compiler to compile.
 *
 * The HashLink benchmark compares a script against the same program written as Haxe and compiled
 * ahead of time, which means the same corpus has to exist twice: once as source text for the
 * interpreter and the emitter, and once as real declarations for `haxe` to build. Writing it twice
 * by hand is how the two quietly stop being the same program, and then the comparison measures the
 * difference between two corpora rather than between two ways of running one.
 *
 * So it is written once, in `ModeCases`, and this generates the other. Run with `--interp` before
 * the benchmark builds; `run.sh` does it.
 *
 * The transform is three substitutions and nothing clever. A case's module is already a class with a
 * static `run`, so it needs a name of its own, and any helper class it declares needs one too, since
 * every case ends up in one file and several of them call their helper `Holder`.
 *
 * The scale is compiled in. A case's loop bound is written into its source by `ModeCases.all(n)`, so
 * a natively compiled case cannot take it at run time the way a script can. The generated file
 * records which `n` it was built for, and the harness refuses to run at any other, because two
 * columns measured at two scales is not a comparison.
 */
class GenNative {
	/**
	 * Cases Haxe itself will not compile, and why.
	 *
	 * `noCall` is one assignment per iteration and nothing else, which is the point of it: it is the
	 * baseline the other `op` cases are read against. Written out, that assignment is `s = s`, and
	 * Haxe rejects it outright as assigning a value to itself. Rewriting it into something Haxe
	 * accepts would measure a different operation and quietly stop being the case the other two
	 * suites run, so the native columns report it unsupported and carry this reason instead.
	 */
	static var SKIP:Map<String, String> = ['noCall' => 'Haxe rejects `s = s` as assigning a value to itself'];

	public static function main():Void {
		/**
		 * Through the environment rather than through arguments, for the reason the conformance
		 * driver gives: this runs under `--interp`, where the compiler takes the command line for
		 * itself and rejects an option it does not know.
		 */
		var passed:String = Sys.getEnv('HXS_GEN');
		var args:Array<String> = passed == null ? [] : passed.split(' ');

		var n:Int = args.length > 0 ? Std.parseInt(args[0]) : 100000;
		var out:String = args.length > 1 ? args[1] : 'bin_hlbench/gen/NativeCases.hx';

		var cases:Array<ModeCases.Case> = ModeCases.all(n);
		var b:StringBuf = new StringBuf();

		b.add('// Generated by test/bench/hlbench/GenNative.hx. Do not edit.\n');
		b.add('// The corpus is test/bench/mbench/ModeCases.hx; this is that corpus as Haxe.\n\n');

		b.add('class NativeCases {\n');
		b.add('\t/** The loop count these were generated for, which the harness checks it was asked for. */\n');
		b.add('\tpublic static inline var SCALE:Int = ' + n + ';\n\n');

		/**
		 * The bound the generated loops actually read, and the reason it is not the literal.
		 *
		 * Haxe compiles these for real, and a real compiler handed `while (i < 100000) { s = i * 2 - i; }`
		 * with nothing escaping proves the answer and emits no loop at all. Twenty-seven of the cases
		 * measured 0.0000 us/iter that way, which is not a floor to compare a script against: it is the
		 * benchmark being synthetic rather than the language being fast. Read through a mutable static
		 * whose value the compiler cannot see, the loop has to run.
		 *
		 * It still equals `SCALE`, since the harness refuses to run at any other, so every expected
		 * value stays exact.
		 */
		b.add('\t/** The bound the loops read, opaque to the optimiser so it cannot fold them away. */\n');
		b.add('\tpublic static var N:Int = scaleAtRuntime();\n\n');
		b.add('\tstatic function scaleAtRuntime():Int {\n');
		b.add('\t\tvar written:String = Sys.getEnv("HLBENCH_N");\n');
		b.add('\t\tvar v:Null<Int> = written == null ? null : Std.parseInt(written);\n');
		b.add('\t\treturn v == null ? SCALE : v;\n');
		b.add('\t}\n\n');

		b.add('\t/** Every case, in corpus order. */\n');
		b.add('\tpublic static function names():Array<String> {\n\t\treturn [');
		b.add([for (c in cases) '"' + c.n + '"'].join(', '));
		b.add('];\n\t}\n\n');

		b.add('\t/** @return The case\'s tier, for reporting it beside the others. */\n');
		b.add('\tpublic static function tier(name:String):String {\n\t\treturn switch (name) {\n');
		for (c in cases)
			b.add('\t\t\tcase "' + c.n + '": "' + c.t + '";\n');
		b.add('\t\t\tcase _: "?";\n\t\t}\n\t}\n\n');

		b.add('\t/** @return What the case must produce, which is what stops a folded loop reading as fast. */\n');
		b.add('\tpublic static function expected(name:String):String {\n\t\treturn switch (name) {\n');
		for (c in cases)
			b.add('\t\t\tcase "' + c.n + '": "' + c.x + '";\n');
		b.add('\t\t\tcase _: "?";\n\t\t}\n\t}\n\n');

		b.add('\t/** @return Why Haxe cannot compile this case, or null when it can. */\n');
		b.add('\tpublic static function skipped(name:String):Null<String> {\n\t\treturn switch (name) {\n');
		for (name => why in SKIP)
			b.add('\t\t\tcase "' + name + '": "' + why + '";\n');
		b.add('\t\t\tcase _: null;\n\t\t}\n\t}\n\n');

		b.add('\t/** Runs one case by name. */\n');
		b.add('\tpublic static function run(name:String):Dynamic {\n\t\treturn switch (name) {\n');
		for (c in cases) {
			if (!SKIP.exists(c.n))
				b.add('\t\t\tcase "' + c.n + '": C_' + c.n + '.run();\n');
		}
		b.add('\t\t\tcase _: null;\n\t\t}\n\t}\n}\n');

		for (c in cases) {
			if (SKIP.exists(c.n))
				continue;
			b.add('\n');
			b.add(asHaxe(c));
		}

		var dir:String = out.substr(0, out.lastIndexOf('/'));
		if (dir.length > 0 && !sys.FileSystem.exists(dir))
			sys.FileSystem.createDirectory(dir);

		var written:Int = 0;
		for (c in cases) {
			if (!SKIP.exists(c.n))
				written++;
		}

		sys.io.File.saveContent(out, b.toString());
		Sys.println('wrote ' + out + ': ' + written + ' of ' + cases.length + ' cases at n=' + n);
	}

	/**
	 * One case's module as ordinary Haxe.
	 *
	 * @param c The case.
	 * @return Its declarations, named so that every case can share one file.
	 */
	static function asHaxe(c:ModeCases.Case):String {
		var src:String = c.s;

		src = StringTools.replace(src, 'package p;\n', '');
		src = StringTools.replace(src, 'class T {', 'class C_' + c.n + ' {');

		// Several cases declare a helper and all of them call it `Holder`, which one file cannot hold
		// twice. Word-bounded so a `Holder` inside a string or a longer name is left alone; none of
		// the corpus has one, and the check is cheaper than finding out later that it did.
		src = new EReg('\\bHolder\\b', 'g').replace(src, 'Holder_' + c.n);

		// The loop bound read rather than written, so the optimiser cannot prove the answer and drop
		// the loop entirely. Word-bounded, so a longer number containing it is left alone.
		src = new EReg('\\b' + c.i + '\\b', 'g').replace(src, 'NativeCases.N');

		return src;
	}
}
